# Generated by Django 4.0.1 on 2022-02-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_expiredtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default='2For20', max_length=50),
            preserve_default=False,
        ),
    ]
